### ISSUE TITLE
Sort analyzer not totally correct

### ISSUE THREAD

**Issue by gsmet** [openwide-java/owsi-core-parent#42]
Hi,

In https://github.com/openwide-java/owsi-core-parent/blob/master/owsi-core/owsi-core-components/owsi-core-component-jpa-more/src/main/java/fr/openwide/core/jpa/more/business/parameter/model/Parameter.java#L86 , I'm wondering if the TrimFilterFactory should be moved at the end of the analyzer stack?
## 

Guillaume

**Comment by yrodiere** [comment]
Fixed. Thanks!
